### ISSUE TITLE
Offset when velocity changes sign

### ISSUE THREAD

**Issue by martincmartin** [kristopherjohnson/lunar-c#1]
Hi,

Thanks for doing this conversion!

The constant at the end of the line:

S = M * V / (Z * K * (W + sqrt(W * W + V / Z))) + 0.5;

Should be 0.05, not 0.5.

This code is invoked when the lander switches from moving down to up in a single time step.  This code computes an approximate time when the velocity is zero and the lander is at its minimum position, so we can see whether or not it hits the moon.  I'm not sure what the offset is for, maybe to make sure we're a little past the zero of velocity, so we don't get stuck in an infinite loop of checking where the velocity changes sign.

Anyway, both the original FOCAL and the BASIC version in "BASIC Computer Games" have 0.05, so I think that's correct.

**Comment by kristopherjohnson** [comment]
Thank you. I was just about to post your blog article as a known issue. https://martincmartin.com/2024/06/14/how-i-found-a-55-year-old-bug-in-the-first-lunar-lander-game/

**Comment by kristopherjohnson** [comment]
Fixed: https://github.com/kristopherjohnson/lunar-c/commit/66790acef15ebb7fc58f026ea5817f5ff074544b
